### ISSUE TITLE
/bin/sh: 0: Illegal option -

### ISSUE THREAD

**Issue by DestBro** [dajobe/hbase-docker#28]
![image](https://user-images.githubusercontent.com/34140558/57300012-99638e80-70de-11e9-8de8-64443b8d1dae.png)

Step 5/17 : RUN /build/prepare-hbase.sh &&     cd /opt/hbase && /build/build-hbase.sh     cd / && /build/cleanup-hbase.sh && rm -rf /build
 ---> Running in c2a56b388f68

/bin/sh: 0: Illegal option -

Service 'hbase' failed to build: The command '/bin/sh -c /build/prepare-hbase.sh &&     cd /opt/hbase && /build/build-hbase.sh     cd / && /build/cleanup-hbase.sh && rm -rf /build' returned a non-zero code: 2

**Comment by bigshaqmnh** [comment]
Hello! Need help, I faced the same issue and can't get how to solve it =(
May be you remember how you did it??
