### ISSUE TITLE
Does This Support Fully Distributed or Pseudo-Distributed Scaling?

### ISSUE THREAD

**Issue by hasancansaral** [dajobe/hbase-docker#9]
Hi, just a quick question: Can I scale an HBase cluster (preferable with HDFS, but not a definitive requirement) using this? Or should the data be definitely inside the container? I can see that I can make multiple containers use the same /data `VOLUME` (persistent volume in Kubernetes, for example). Maybe by making them network on the host level (I am using a single hardware for my nodes, maybe I can make them all use the host's network - not sure how that would be using Cloudstack VMs though). Thanks!

**Comment by dajobe** [comment]
This is just for getting an hbase in a box, not a clustered hbase

**Comment by hasancansaral** [comment]
Thanks!

**Comment by hasancansaral** [comment]
@dajobe Do you remember the repository that has been mentioned here but now gone somehow?
